version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bejee
      POSTGRES_PASSWORD: 634G9V2PBfWe
      POSTGRES_DB: todo
    ports: 
      - 5432:5432
  backend:
    build: ./backend
    image: backend
    container_name: backend
    ports:
      - 3000:3000
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - backend